export const METAMASK_UPDATED = "METAMASK_UPDATED";

export const ACTION_ALLOWANCE_UPDATED = "ACTION_ALLOWANCE_UPDATED"; 
export const FACTORY_ALLOWANCE_UPDATED = "FACTORY_ALLOWANCE_UPDATED";
export const SPAD_TOKENS_UPDATED = "SPAD_TOKENS_UPDATED";

export const TRANSACTION_SUBMITTED = "TRANSACTION_SUBMITTED";
export const CLOSE_TRANSACTION_MODAL = "CLOSE_TRANSACTION_MODAL";

export const TWITTER_HANDLE_VERIFIED = "TWITTER_HANDLE_VERIFIED";
export const CHANGE_NETWORK_MODAL = "CHANGE_NETWORK_MODAL";